config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/rv10admin', as: 'rails_admin'
  resources :products
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'store#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_many :line_items

  # mount_uploader :image, ImageUploader
  mount_uploader :photo, PhotoUploader
  # serialize :image, JSON #if you use SQlite, add this line

  validates :name, :price, :category, :color, :quantity, :size, :gender, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum alowed. "}
  validates :price, numericality: { only_integer:true }, length: { maximum: 7 }

  COLOR = %w{ Blanco Negro Rojo Azul Amarillo Verde Beige }
  SIZE = %w{ XS S M L XL }
  GENDER = %W{ Male Female }
  CATEGORY = %W{ Vestidos Bikini Malla Shorts Blusas Camisas}


 private

  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("created_at desc")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :color, :quantity, :size, :gender, :image, :photo, :category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

def product_author(product)
  user_signed_in? && current_user.id == product.user.id
end

end

app/views/products/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @product, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :name , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :quantity, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Color</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :color, collection: Product::COLOR, prompt: "Select color" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>


          <div class="field column is-4">
            <div class="control">
              <label class="label">Size</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :size, collection: Product::SIZE, prompt: "Select size" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Gender</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :gender, collection: Product::GENDER, prompt: "Select gender" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-venus-mars"></i>
                </span>
              </div>
            </div>
           </div>
         </div>


            <div class="control">
              <label class="label">Category</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :category, collection: Product::CATEGORY, prompt: "Select Category" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>



        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                 <%= f.input :photo, as: :file, input_html: { class:"file-input product-image" }, label: false, wrapper: false %>


                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />



        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-white' %>
            <%= link_to 'Cancel', products_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% content_for :header do %>
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest products on Rv10
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="instrument-index-grid pt4">
  <% @products.each do |product| %>

    <div class="instrument border-light" style="width:100%; height:100%;">
      <div class="instrument-thumb" style="
    height: auto;
    max-width: 244px;
">

       <a href="#"><%= cl_image_tag product.photo%></a>

      <% if product.price? %>
        <div class="condition">
          <span class="tag is-dark">Bs. <%= product.price %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>

      <p class="has-text-gray fg pt1"><%= product.description %></p>

      <p class="has-text-gray fg pt1"><%= product.size %></p>
      <p class="has-text-gray fg pt1"><%= product.color %></p>
      <p class="has-text-gray fg pt1"><%= product.category %></p>
     <!--  <p class="f3 fw6 has-text-right pt2 price">Bs.<%=(product.price) %></p> -->

      <%# if product_author(product) %>
         <%#= link_to 'Edit', edit_product_path(product), class: "button is-small" %>
         <%#= link_to 'Delete', product, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <%# end %>

    </div>
  </div>
  <% end %>
</div>

app/views/products/new.html.erb
<% content_for :header do %>
<section class="hero is-white">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell a Product
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2" style="
    color: darkred !important;
"><%= @product.name %></h1></h1>


      <ul class="pv1">
        <% if @product.color? %>
        <li class="inline-block pr3"><%= @product.color %></li>
        <% end %>

        <li class="inline-block pr3"><%= @product.gender %></li>

        <% if @product.size? %>
        <li class="inline-block pr3"><%= @product.size %></li>
        <% end %>
      </ul>


      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4"><%= @product.name %></h3>


      </br>
      <div class="feature-image">
      <%= cl_image_tag @product.photo%>
    </div>


 <h3 class="subtitle is-4"></h3>
      <%= @product.description %>

      <h3 class="subtitle is-4 pt5">Descripcion</h3>

      <table class="table is-narrow">
        <% if @product.size %>
        <tr>
          <td class="has-text-weight-bold">Gender</td>
          <td><%= @product.gender %></td>
        </tr>
        <% end %>

        <% if @product.color %>
          <tr>
            <td class="has-text-weight-bold">Color:</td>
            <td><%= @product.color %></td>
          </tr>
        <% end %>

        <% if @product.size %>
          <tr>
            <td class="has-text-weight-bold">Size:</td>
            <td><%= @product.size %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Price:</td>
          <td>Bs.<%=@product.price %></td>
        </tr>
      </table>
    </div>
    </div>



    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered" style="
    color: darkred !important;
">Bs. <%=(@product.price) %></h4>

        <p class="has-text-centered mb4">Sold by <%= @product.user.name %></p>
               <%= button_to 'Add to cart', line_items_path(product_id: @product), class: 'button is-warning add-to-cart select is-fullwidth' %>


      </div>
      </div>
    </div>
  </div>

</section>